# Generated by Django 5.2.7 on 2025-10-30 03:32

import localflavor.in_.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address_2',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='location',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=localflavor.in_.models.INStateField(default='KA', max_length=2),
        ),
    ]
