# Generated by Django 5.2.7 on 2025-11-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_listing_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.DecimalField(default=0.00, max_digits=10, decimal_places=2),
            preserve_default=False,
        ),
    ]
