# Generated by Django 5.2.7 on 2025-11-02 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_listing_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='price',
        ),
    ]
